name: Apprenticeship App Unit Tests
description: Tests the behavior of the developed web app
runs:
  using: composite
  steps:
  - uses: actions/setup-node@v3
    with:
      node-version: '16'
  - run: cd $GITHUB_ACTION_PATH && npm install --production
    shell: bash
  - run: node $GITHUB_ACTION_PATH/index.js
    shell: bash
