name: 'GitOps GitHub Pull Request (YAML)'
description: 'Update YAML value and create GitHub Pull Request'
inputs:
  repo:
    description: 'GitHub repo to update'
    required: true
  token:
    description: 'GitHub personal access token (PAT)'
    required: true
  file:
    description: 'File to update'
    required: true
  path:
    description: 'Path expression of value to update'
    required: true
  value:
    description: 'New value to set'
    required: true
  merge:
    description: 'Automatically merge pull request'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_REPO: ${{ inputs.repo }}
    GITHUB_TOKEN: ${{ inputs.token }}
    MANIFEST_FILE: ${{ inputs.file }}
    MANIFEST_PATH: ${{ inputs.path }}
    MANIFEST_VALUE: ${{ inputs.value }}
    MERGE_PR: ${{ inputs.merge }}