name: Oauth2 Token
description: Uses the client credentials grant to provide an access token for external services
inputs:
  clientId:
    description: The client identifier
    required: true
  clientSecret:
    description: The client secret for the given clientId
    required: true
  tokenUrl:
    description: OAuth2 server token url.
    required: true
  scopes:
    description: A space delimited list of oauth2 scopes to request.
    required: false
    default: ""
runs:
  using: docker
  image: Dockerfile
  env:
    CLIENT_ID: ${{ inputs.clientId }}
    CLIENT_SECRET: ${{ inputs.clientSecret }}
    SCOPES: ${{ inputs.scopes }}
    TOKEN_URL: ${{ inputs.tokenUrl }}
