name: 'Upload Github release asset'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    REPO: ${{ inputs.REPO }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    ORG_OWNER: ${{ inputs.ORG_OWNER }}
    RELEASE: ${{ inputs.RELEASE }}
    FILE: ${{ inputs.FILE }}

description: 'Deploy a binary artifact to Github Releases'
inputs: 
  GITHUB_TOKEN: 
    description: 'Github token to authenticate with Github'
    default: ""
    required: true

  REPO: 
    description: 'Github repo name'
    default: ""
    required: true
    
  ORG_OWNER: 
    description: 'Github orginization owner'
    default: 'liatrio'
    required: false
  
  FILE: 
    description: 'Binary file to upload to Github Releases'
    default: ""
    required: true

  RELEASE:
    description: 'Release name'
    default: 'latest'
    required: false
