name: 'GitOps GitHub Pull Request'
description: 'Create GitHub Pull Request with current changes'
inputs:
  repo:
    description: 'GitHub repo to update'
    required: true
  token:
    description: 'GitHub personal access token (PAT)'
    required: true
  commit-prefix:
    description: 'Prefixed to the git commit message'
    required: false
    default: 'gitops'
  git-email:
    description: 'Git'
    required: false
    default: 'gitops@liatr.io'
  git-name:
    description: 'Git'
    required: false
    default: 'GitOps Automation'
  message:
    description: 'Git commit message'
    required: true
  merge-auto:
    description: 'Set non empty string to automatically merge pull request'
    required: false
    default: ''
  merge-type:
    description: 'Type of merge. Only applies if merge-auto is set. [squash(default)|rebase|merge]'
    required: false
    default: 'squash'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_REPO: ${{ inputs.repo }}
    GITHUB_TOKEN: ${{ inputs.token }}
    COMMIT_MESSAGE: ${{ inputs.message }}
    COMMIT_PREFIX: ${{ inputs.commit-prefix }}
    GIT_EMAIL: ${{ inputs.git-email }}
    GIT_NAME: ${{ inputs.git-name }}
    MERGE_AUTO: ${{ inputs.merge-auto }}
    MERGE_TYPE: ${{ inputs.merge-type }}
