name: Conventional Release
description: Generates the next semantic version based on conventional commits, then creates a release and tag.
inputs:
  debug:
    description: "Whether semantic-release should run in debug mode"
    required: false
    default: ""
  dryRun:
    description: "Controls if semantic-release performs the release"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
    - uses: azure/setup-helm@v1
      with:
        version: '3.8.0'
    - run: yarn install --production
      shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
        DRY_RUN: ${{ inputs.dryRun }}
        