name: Conventional Release
description: Generates the next semantic version based on conventional commits, then creates a release and tag.
inputs:
  debug:
    description: "Whether semantic-release should run in debug mode"
    required: false
    default: ""
  dryRun:
    description: "Controls if semantic-release performs the release"
    required: false
    default: ""
outputs:
  newVersion:
    description: "The new version tag outputted by Semantic Release"
    value: ${{ steps.entrypoint.outputs.newVersion }}
  changed:
    description: "A string stating if there is a new release or not."
    value: ${{ steps.entrypoint.outputs.changed }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: azure/setup-helm@v1
      with:
        version: '3.8.0'
    - run: cd $GITHUB_ACTION_PATH && yarn install --production
      shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      id: entrypoint
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
        DRY_RUN: ${{ inputs.dryRun }}
