name: snow-attach-file
description: Attach a file to a change request or other ticket
inputs:
  filePath:
    description: Path to the file, including the file name
    required: true
  fileContentType:
    description: Content type of the file
    default: "application/text"
    required: false
  requestSysId:
    description: Sysid of the target request
    required: true
  serviceNowInstanceUrl:
    description: Base URL of the ServiceNow instance
    required: true
  serviceNowUsername:
    description: ServiceNow username
    required: true
  serviceNowPassword:
    description: ServiceNow user password
    required: true
  tableName:
    description: Table in ServiceNow associated with requestSysId. Override this to attach to incidents or item requests.
    default: change_request
    required: false
runs:
  using: docker
  image: Dockerfile
