#!/bin/sh -l
set -e

export GITOPS_GIT_URL=$INPUT_URL
export GITOPS_GIT_USERNAME=$INPUT_USERNAME
export GITOPS_GIT_PASSWORD=$INPUT_PASSWORD
export GITOPS_REPO_FILE=$INPUT_FILE
export GITOPS_VALUES=$INPUT_VALUES

gitty-up
