name: Replace Secret and Base64 Encode
description: Replaces the secret token and base64 encodes to string
inputs:
  token:
    description: The secret token to replace
    required: true
  file:
    description: The name of the specific account to use
    required: true
  replace-key-entropy:
    description: openssl rand -hex <entropy>
    required: false
    default: "8"
outputs:
  base64-encoded:
    description: The base64 encoded file with pat replaced
    value: ${{ steps.encode.outputs.base64-encoded }}
  replacement-key:
    description: The pat replacement key
    value: ${{ steps.encode.outputs.replacement-key }}

runs:
  using: composite
  steps:
    - name: Base64 Encode File
      shell: bash
      env:
        FILE_PATH: ${{ inputs.file }}
      id: encode
      run: |
        big_rand="$(openssl rand -hex ${{ inputs.replace-key-entropy }})" || { print "There was a problem openssl. Exiting ...\n" >&2; exit 1; }
        encoded=$(echo $(cat "${FILE_PATH}" | sed "s/${{ inputs.token }}/${big_rand}/g" | base64))

        echo "base64-encoded=$(echo ${encoded})"
        echo "base64-encoded=$(echo ${encoded})" >> $GITHUB_OUTPUT

        echo "replacement-key=${big_rand}"
        echo "replacement-key=${big_rand}" >> $GITHUB_OUTPUT