name: Build

on:
  push:
    branches:
      - master
    paths:
      - 'apprentice-action/**'
      - 'conventional-pr-title/**'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: ['conventional-pr-title', 'apprentice-action']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Docker Tag
        id: tag
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.action }}
          push: true
          tags: |
            ghcr.io/liatrio/github-actions/${{ matrix.action }}:latest
            ghcr.io/liatrio/github-actions/${{ matrix.action }}:${{ steps.tag.outputs.tag }}
