name: Conventional Release

on:
  push:
    branches:
      - master
    paths:
      - 'conventional-release/**'
      - '.github/workflows/conventional-release.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Docker Tag
        id: tag
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: conventional-release
          push: true
          tags: |
            ghcr.io/liatrio/github-actions/conventional-release:latest
            ghcr.io/liatrio/github-actions/conventional-release:${{ steps.tag.outputs.tag }}
